modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      #headers:
      #  Host: vhost.example.com
      #  Accept-Language: en-US
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      fail_if_matches_regexp:
      - "Could not connect to database"
      #fail_if_not_matches_regexp:
      #- "Download the latest version here"
  icmp:
    prober: icmp
    timeout: 5s
