#https://github.com/coreos/etcd/tree/release-2.3
version: '2'
services:
  etcd:
    image: quay.io/coreos/etcd:v2.3.6
    hostname: etcd
    restart: always
    expose:
      - 2379 #client api
      - 2380 #cluster communication
    ports:
      - 127.0.0.1:2379:2379
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://localhost:2379,http://etcd:2379
  browser:
    image: etcd-browser
    hostname: etcd-browser
    restart: always
    ports:
      - 8000:8000
    environment:
      - AUTH_USER=admin
      - AUTH_PASS=${ETCD_BROWSER_PASSWD}
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
      - SERVER_PORT=8000
  registrator:
    image: gliderlabs/registrator
    hostname: registrator
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal -resync 60 etcd://etcd:2379/balancer
  nginx:
    image: nginx-confd
    restart: always
    volumes:
      - ./confd/:/etc/confd/
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    network_mode: host
