version: '2'
services:

  etcd:
    image: quay.io/coreos/etcd:v3.0.15
    hostname: etcd
    restart: always
    expose:
      - 2379 #client api
      - 2380 #cluster communication
    ports:
      - 2379:2379
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://192.168.0.115:2379,http://etcd:2379

  viewer:
    image: nikfoundas/etcd-viewer
    hostname: etcd-viewer
    restart: always
    ports:
      - 8080:8080

  registrator:
    image: gliderlabs/registrator
    restart: always
    hostname: registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -retry-attempts -1 -retry-interval 10000 -ip 192.168.0.115 -resync 10 etcd://192.168.0.115:2379 # -ip - which ip will be registered for all services

  nginx:
    image: nginx-confd:1.11
    build: ./nginx-confd
    restart: always
    volumes:
      - ./confd/:/etc/confd/
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    network_mode: host

