version: '2'
services:

  registry:
    image: registry:2
    hostname: dockerregistry.example.com
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./registry/:/var/lib/registry/
      - ./certs/:/certs/
      - ./auth/:/auth/
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_STORAGE_DELETE_ENABLED=true
