version: '2'
services:
  traefik:
    image: traefik
    command: -c /etc/traefik/traefik.toml
    #network_mode: host
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml


