version: '2'
services:
  nexus:
    image: sonatype/nexus3
    restart: always
    hostname: nexus
    ports:
      - 8081:8081
      - 8082:8082 #port for docker registry
    volumes:
      - ./nexus-data/:/nexus-data/
