version: '2'
services:

  elasticsearch:
    image: elasticsearch
    hostname: elasticsearch
    restart: always
    volumes:
      - ./esdata/:/usr/share/elasticsearch/data/
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300

  logstash:
    image: logstash
    hostname: logstash
    restart: always
    command: logstash --auto-reload -f /etc/logstash/conf.d/
    ports:
      - 5044:5044
    volumes:
      - ./conf/logstash.conf.d/:/etc/logstash/conf.d/
      - ./conf/patterns/:/etc/logstash/patterns/

  kibana:
    image: kibana
    hostname: kibana
    restart: always
    environment:
      NODE_OPTIONS: --max-old-space-size=200
      ELASTICSEARCH_URL: http://elasticsearch:9200
    expose:
      - 5601

  nginx:
    image: nginx
    hostname: elknginx
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/htpasswd:/etc/nginx/htpasswd
      - ./conf/certs/:/etc/nginx/certs/
    ports:
      - 5601:5601
